apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: sahashop
  labels:
    environment: web
    app: backend
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "512Mi"
        cpu: "300m"
      limits:
        memory: "1024Mi"
        cpu: "500m"
    env:
      - name: app_name
        valueFrom: 
          configMapKeyRef:
            name: nginx # must match configMap define name
            key: APP_NAME
      - name: sahashop
        valueFrom: 
          configMapKeyRef:
            name: nginx
            key: APP_VERSION
      - name: database_url
        valueFrom: 
          configMapKeyRef:
            name: nginx
            key: DATABASE_URL
    ports:
      - containerPort: 80