apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: sahashop
  labels:
    environment: web
    app: backend
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "512Mi"
        cpu: "300m"
      limits:
        memory: "1024Mi"
        cpu: "500m"
    envFrom:
        - secretRef:
            name: nginx-secret
    ports:
      - containerPort: 80