apiVersion: v1
kind: PersistentVolume
metadata:
  name: sahashop-efs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0a4ce1afad99b8741
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sahashop-efs
spec:
  volumeName: sahashop-efs
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static
  labels:
    purpose: efs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run -v hostpath:contaierpath
    - name: sahashop-efs
      mountPath: /usr/share/nginx/html
  volumes:
  - name: sahashop-efs
    persistentVolumeClaim:
      claimName: sahashop-efs
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    nodePort: 30007