apiVersion: v1
kind: Pod
metadata: 
  name: multipod
  namespace: sahashop
spec:
  containers:
  - name: nginx-web
    image: nginx
    ports:  
    - containerPort: 80
  # multicontainer
  - name: almalinux
    image: almalinux:8
    command: ["sleep","1000"]