kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: sahashop
  labels:  
    module: backend
    environment: web
    managed: sahaja
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80