apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: sahashop 
  labels:
    name: redis
    project: sahashop
    tier: db 
spec:
  replicas: 1
  selector:
    matchLabels: # should match with pod
      name: redis
      project: sahashop
      tier: db
  template: # pod defination
    metadata:
      labels: # pod labels
        name: redis
        project: sahashop
        tier: db
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: sahashop
spec:
  selector:
    name: redis
    project: sahashop
    tier: db 
  ports:
  - protocol: TCP
    port: 6379 #service-port
    targetPort: 6379 #container-port
